- name: Install Java 
  package:
    name: java 
    state: installed 

- name: Create app user 
  user:
    name: student 

- name: Find latest version of Tomcat 
  shell: "curl -s 'https://archive.apache.org/dist/tomcat/tomcat-8/?C=M;O=A' | grep folder.gif | tail -1  | awk '{print $5}' | awk -F = '{print $2}' |sed -e 's/\"/ /g' |xargs -n1  |head -1 | sed -e 's/v//' -e 's|/||'"
  register: out 

- name: Declare Variables 
  set_fact:
    TOMCAT_VERSION: "{{out.stdout}}"
  
- name: Print version 
  debug:
    msg: "{{TOMCAT_VERSION}}"