- name: Install Java 
  package:
    name: java 
    state: installed 

- name: Create app user 
  user:
    name: student 

- name: Find latest version of Tomcat 
  shell: "curl -s 'https://archive.apache.org/dist/tomcat/tomcat-8/?C=M;O=A' | grep folder.gif | tail -1  | awk '{print $5}' | awk -F = '{print $2}' |sed -e 's/\"/ /g' |xargs -n1  |head -1 | sed -e 's/v//' -e 's|/||'"
  register: out 

- name: Declare Variables 
  set_fact:
    TOMCAT_VERSION: "{{out.stdout}}"
    TOMCAT_HOME: "/home/student/apache-tomcat-{{out.stdout}}"
  
- name: Download Tomcat 
  unarchive:
    src: http://apachemirror.wuchna.com/tomcat/tomcat-8/v{{TOMCAT_VERSION}}/bin/apache-tomcat-{{TOMCAT_VERSION}}.tar.gz 
    dest: /home/student
    remote_src: yes 
  become_user: student

- name: Remove old wars
  file:
    path: "{{item}}"
    state: absent 
  loop:
    - "{{TOMCAT_HOME}}/webapps/student.war"
    - "{{TOMCAT_HOME}}/webapps/student"

- name: Download app war 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest: "{{TOMCAT_HOME}}/webapps/student.war"
  