- name: Install Java 
  package:
    name: java 
    state: installed 

- name: Create app user 
  user:
    name: student 

- name: Find latest version of Tomcat 
  shell: "curl -s 'https://archive.apache.org/dist/tomcat/tomcat-8/?C=M;O=A' | grep folder.gif | tail -1  | awk '{print $5}' | awk -F = '{print $2}' |sed -e 's/\"/ /g' |xargs -n1  |head -1 | sed -e 's/v//' -e 's|/||'"
  register: out 

- name: Declare Variables 
  set_fact:
    TOMCAT_VERSION: "{{out.stdout}}"
    TOMCAT_HOME: "/home/student/apache-tomcat-{{out.stdout}}"
  
- name: Download Tomcat 
  unarchive:
    src: http://apachemirror.wuchna.com/tomcat/tomcat-8/v{{TOMCAT_VERSION}}/bin/apache-tomcat-{{TOMCAT_VERSION}}.tar.gz 
    dest: /home/student
    remote_src: yes 
  become_user: student

- name: Remove old wars
  file:
    path: "{{item}}"
    state: absent 
  loop:
    - "{{TOMCAT_HOME}}/webapps/student.war"
    - "{{TOMCAT_HOME}}/webapps/student"

- name: Download app war 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest: "{{TOMCAT_HOME}}/webapps/student.war"
  become_user: student

- name: Download JDBC Driver
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar
    dest:  "{{TOMCAT_HOME}}/lib/mysql-connector.jar"
  become_user: student

- name: Copy Context.xml 
  copy:
    src: context.xml
    dest:  "{{TOMCAT_HOME}}/conf/context.xml"
  become_user: student

- name: Setup tomcat init script 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/tomcat-init
    dest: /etc/init.d/tomcat 
    mode: 0755

- name: Reload daemon 
  shell: systemctl daemon-reload 

- name: Restart Tomcat 
  service:
    name: tomcat 
    state: restarted 
    enabled: yes 

- name: Remove API 
  file:
    path: /home/student/api
    state: absent 
  
- name: Create API directory 
  file:
    path: /home/student/api 
    state: directory 
  become_user: student 

- name: Copy DB env file 
  copy:
    src: db-details
    dest: /home/student/.db-details 
  become_user: student

- name: Update bash_profile 
  lineinfile:
    path: /home/student/.bashrc
    line: source /home/student/.db-details 

- name: Download API war 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/studentapi.war
    dest: /home/student/api/studentapi.war 
  become_user: student 

- name: Download api init 
  get_url: 
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/studentapi-init
    dest: /etc/init.d/studentapi
    mode: 0755 

- name: Reload daemon  API 
  shell: systemctl daemon-reload 

- name: Restart API 
  service:
    name: studentapi
    state: restarted 
    enabled: yes 
